name:                DMCTS
version:             0.1.0
github:              "joshjet/DMCTS"
license:             BSD3
author:              "Joshua David Christensen"
maintainer:          "u0978248@utah.edu"
copyright:           "Joshua David Christensen 2021"

description:         Please see the README on GitHub at <https://github.com/joshjet/DMCTS#readme>

dependencies:
- base >= 4.7 && < 5
- aws-lambda-haskell-runtime >= 3.0.0
- aeson

library:
  source-dirs: src

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - DMCTS

default-extensions:
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
