AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An API Driven dmcts-runtime
Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  runtime:
    Type: AWS::Serverless::Function
    Properties:
      Description: The DMCTS Runtime
      PackageType: Image
      ImageUri: 544864025547.dkr.ecr.us-west-1.amazonaws.com/dmcts-runtime-lambda:latest-dev
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref api
            Path: /
            Method: POST

