name:                dmcts-knapsack
version:             0.1.0
github:              "joshjet/DMCTS"
license:             BSD3
author:              "Joshua David Christensen"
maintainer:          "u0978248@utah.edu"
copyright:           "Joshua David Christensen 2021"

description:         Please see the README on GitHub at <https://github.com/joshjet/DMCTS#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- dmcts-encoding

library:
  source-dirs: src

executables:
  app-specific-code:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
      - -with-rtsopts=-N
    dependencies:
      - dmcts-knapsack
      - hspec
      - dmcts-encoding

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: dmcts-runtime

default-extensions:
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric

build-tools:
  - hspec-discover == 2.*
