name:                dmcts-encoding
version:             0.1.0
github:              "joshjet/DMCTS"
license:             BSD3
author:              "Joshua David Christensen"
maintainer:          "u0978248@utah.edu"
copyright:           "Joshua David Christensen 2021"

description:         Please see the README on GitHub at <https://github.com/joshjet/DMCTS#readme>

dependencies:
- base >= 4.7 && < 5
- aeson

library:
  source-dirs: src
  exposed-modules: PersonEnc

default-extensions:
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
