name:                dmcts-encoding
version:             0.1.0
github:              "joshjet/DMCTS"
license:             BSD3
author:              "Joshua David Christensen"
maintainer:          "u0978248@utah.edu"
copyright:           "Joshua David Christensen 2021"

description:         Please see the README on GitHub at <https://github.com/joshjet/DMCTS#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - containers
  - random

library:
  source-dirs: src
  exposed-modules:
    - DMCTS.Types
    - DMCTS.PersonEnc
    - DMCTS.SearchTree

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: dmcts-encoding

default-extensions:
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric

build-tools:
  - hspec-discover == 2.*
